export default {
  user: {
    user_id: 1,
    isLoggedIn: false,
    location: null,

    // profile: {
    //   avatar: 'https://i.ytimg.com/vi/1v6M41Divso/maxresdefault.jpg',
    //   name: 'Kim Panda',
    //   address: 'back handle lane Austin, VA',
    //   zip: '56352',
    // },
    isDriver: false,
    isRider: false,
    isFetchingUserState: false,
    isChangingAddress: false,
    changeAddressError: false,
    requestUserError: false,
    friends: [],
    addedFriend: null,
  },
  ride: {
    ride_id: 3,
    match: null,
    matchFlag: false,
    directions: null,
    riders: [],
    messages: [],
    isWaitingForMatch: false,
    isAddingDriver: false,
    isRemovingDriver: false,
    isMatched: false,
    isConfirmed: false,
    isCancelling: false,
    isAccepting: false,
    isFetchingMessages: false,
    isPickedUp: false,
    acceptRideError: null,
    rideRequestError: null,
    messagesFetchError: null,
    driverAddError: null,
  },
  routing: {
    locationBeforeTransitions: null,
  },
};
