export default {
  user: {
    user_id: null,
    isLoggedIn: false,
    location: null,
    isDriver: false,
    isRider: false,
    isFetchingUserState: false,
    isChangingAddress: false,
    changeAddressError: false,
    requestUserError: false,
    friends: [],
    addedFriend: null,
  },
  ride: {
    ride_id: 3,
    match: null,
    matchFlag: false,
    directions: null,
    riders: [],
    messages: [],
    isWaitingForMatch: false,
    isAddingDriver: false,
    isRemovingDriver: false,
    isMatched: false,
    isConfirmed: false,
    isCancelling: false,
    isAccepting: false,
    isFetchingMessages: false,
    isPickedUp: false,
    acceptRideError: null,
    rideRequestError: null,
    messagesFetchError: null,
    driverAddError: null,
  },
  routing: {
    locationBeforeTransitions: null,
  },
};
